/*	$NetBSD: mkcxxconfig_h.sh,v 1.1 2014/03/01 10:00:47 mrg Exp $	*/

/* 	This file is automatically generated.  DO NOT EDIT!	 */
/* 	Generated from: NetBSD: mkcxxconfig_h.sh,v 1.1 2014/03/01 10:00:47 mrg Exp 	 */

#ifdef _LP64
#include "bits/aarch64/c++config.h"
#else
#include "bits/arm/c++config.h"
#endif
